<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О проекте',
    'Allow IP {ip} for {org}' => '',
    'Check your email for further instructions.' => '',
    'Email' => '',
    'First Name' => '',
    'Follow the link below to allow IP address {ip}:' => '',
    'Follow the link below to reset your password:' => '',
    'Hello {name}' => '',
    'I agree to the' => '',
    'Last Name' => '',
    'Login or Email' => '',
    'Password' => '',
    'Password reset for {org}' => '',
    'Passwords don\'t match.' => '',
    'Please consider terms of use.' => '',
    'Remember me' => '',
    'Retype password' => '',
    'Sorry, password restore is disabled.' => '',
    'Sorry, signup is disabled.' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'This email has already been taken.' => '',
    'Unable to verify your data submission.' => 'Не удалось проверить переданные данные.',
    'Your account has been successfully created.' => '',
    'terms' => '',
];
