<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О проекте',
    'An email with confirmation instructions was sent to <b>{email}</b>' => 'Письмо с инструкциями для подтверждения отправлено на <b>{email}</b>',
    'Check your email for further instructions.' => 'Проверьте вашу электронную почту для получения дальнейших инструкций.',
    'Confirm password' => 'Подтвердите пароль',
    'Email' => 'Email',
    'Failed confirm email. Please start over.' => 'Не удалось подтвердить email. Пожалуйста, попробуйте всё сначала.',
    'Failed reset password. Please start over.' => 'Не удалось переустановить пароль. Пожалуйста, попробуйте всё сначала.',
    'First Name' => 'Имя',
    'Follow the link below to confirm your email:' => 'Перейдите по ссылке ниже чтобы подтвердить ваш email:',
    'Follow the link below to reset your password:' => 'Перейдите по ссылке ниже чтобы переустановить ваш пароль:',
    'Hello {name},' => 'Здравствуйте, {name}!',
    'I agree to the' => 'Я согласен с',
    'Last Name' => 'Фамилия',
    'Login or Email' => 'Логин или Email',
    'New password was saved.' => 'Новый пароль был сохранён.',
    'Password' => 'Пароль',
    'Password reset for {org}' => 'Восстановление пароля {org}',
    'Passwords don\'t match.' => 'Пароли не совпадают.',
    'Please choose your new password' => 'Пожалуйста, выберите новый пароль',
    'Please confirm your email address!' => 'Пожалуйста, подтвердите ваш email!',
    'Please consider terms of use.' => 'Пожалуйста, учтите правила использования.',
    'Please enter your password' => 'Пожалуйста, введите ваш пароль',
    'Please fill out the following fields to signup' => 'Пожалуйста, заполните поля для регистрации',
    'Please fill out your email. A link to reset password will be sent there.' => 'Пожалуйста, введите ваш email. Туда будет отправлена ссылка на восстановление пароля.',
    'Proceed' => 'Дальше',
    'Remember me' => 'Запомнить меня',
    'Request password reset' => 'Запросить сброс пароля',
    'Reset password' => 'Переустановить пароль',
    'Retype password' => 'Повторите пароль',
    'Sign in' => 'Вход',
    'Signup' => 'Регистрация',
    'Sorry, password restore is disabled.' => 'Извините, восстановления пароля недоступно.',
    'Sorry, signup is disabled.' => 'Извините, регистрация недоступна.',
    'Sorry, we are unable to confirm your email.' => 'Извините, не удалось подтвердить ваш email.',
    'Sorry, we are unable to reset password for email provided.' => 'Извините, мы не можем переустановить пароль для указанной электронной почты.',
    'The entered value is not an email address.' => 'Введенное значение не является емейл адресом.',
    'This email has already been taken.' => 'Этот адрес уже занят.',
    'Unable to verify your data submission.' => 'Не удалось проверить переданные данные.',
    'Your account has been successfully created.' => 'Аккаунт был создан успешно.',
    'Your email was confirmed!' => 'Ваш email был подтверждён!',
    '[{org}] Please confirm your email address' => '[{org}] Пожалуйста, подтвердите ваш email',
    'terms' => 'правилами',
];
