#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/vendor/hiqdev/hiam-core/src/common/config/bootstrap.php');
require(__DIR__ . '/vendor/hiqdev/hiam-core/src/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(Yii::getAlias('@hiam/common/config/main.php')),
    require(Yii::getAlias('@project/common/config/main.php')),
    require(Yii::getAlias('@project/common/config/main-local.php')),
    require(Yii::getAlias('@hiam/console/config/main.php')),
    require(Yii::getAlias('@project/console/config/main.php')),
    require(Yii::getAlias('@project/console/config/main-local.php'))
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
